name: Release service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service_name }}/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build docker image
        run: make build

      - name: Tag the docker image
        id: tag_image
        run: make release

      - uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.tag_image.outputs.next_tag }}
          message: '"${{ steps.tag_image.outputs.next_tag }}: PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"'

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_image.outputs.next_tag }}
          release_name: Release ${{ steps.tag_image.outputs.next_tag }}
