name: Release service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service_name }}/

    steps:
      - uses: actions/checkout@v3

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: '${{ inputs.service_name }}/'
          tag_template: 'yyyy.mm.i'


      - name: Build docker image
        run: make build

      - name: Release docker image
        env:
          VERSION: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        run: make release

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
