name: Service A

on:
  push:
    paths:
      - .github/workflows/a.yaml
      - .github/workflows/service.yaml
      - services/a

jobs:
  call-service-worflow:
    uses: ./.github/workflows/service.yaml
    with:
      service-name: a
