name: Service A

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branch:
      - master
      - main
    paths:
      - .github/workflows/a.yaml
      - services/a/**

jobs:
  test-job:
    if: ${{ github.event.pull_request.merged != true }}
    uses: ./.github/workflows/_service_test.yaml
    with:
      service_name: a

  release-job:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/_service_release.yaml
    with:
      service_name: a
      automatic_deploy_to_dev: true
