name: Service A

on:
  pull_request:
    #    types: [closed]
    branch:
      - master
      - main
    paths:
      - .github/workflows/a.yaml
      - .github/workflows/_*.yaml
      - services/a

jobs:
  pull-request-job:
    uses: ./.github/workflows/_service_test.yaml
    with:
      service_name: a

  push-job:
    #    if: github.event.pull_request.merged == true

    uses: ./.github/workflows/_service_release.yaml
    with:
      service_name: a
