name: Service A

on:
  push:
    paths:
      - services/a

jobs:
  call-service-worflow:
    steps:
      - uses: actions/checkout@v3
        with:
          path: .github

      - uses: ./.github/workflows/service.yaml
        with:
          service-name: a
