name: Service A

on:
  push:
    paths:
      - services/a

jobs:
  checkout:
    steps:
      - uses: actions/checkout@v3

  call-service-worflow:
    uses: ./service.yaml
    with:
      service-name: a
