name: Service B

on:
  push:
    paths:
      - .github/workflows/b.yaml
      - .github/workflows/service.yaml
      - services/b

jobs:
  call-service-worflow:
    uses: ./.github/workflows/service.yaml
    with:
      service_name: b
