name: Service B

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branch:
      - master
      - main
    paths:
      - .github/workflows/b.yaml
      - .github/workflows/_*.yaml
      - services/b/*

jobs:
  test-job:
    if: ${{ github.event.pull_request.merged != true }}
    uses: ./.github/workflows/_service_test.yaml
    with:
      service_name: b

  release-job:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/_service_release.yaml
    with:
      service_name: b
      automatic_deploy_to_dev: true
