name: ci

on:
  workflow_dispatch:
    inputs:
      n:
        description: Magic number
        type: number
        default: 0
        required: false
      greeting:
        description: A greeting message
        type: string
        default: ''
        required: false
  repository_dispatch:
    types: [on-greeting]
jobs:
  greet:
    runs-on: ubuntu-20.04
    steps:
      - name: Greeting
        run: echo "${{ github.event.inputs.greeting }} to you ${{ github.event.inputs.n }} times"
