name: Deploy to Environment With Check

on:
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: 'Git reference to checkout (e.g., main, feature/xyz)'
        required: true
      environment:
        description: 'Target deployment environment (dev, stage, prod)'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Check for successful tests
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if the checkout_ref has a successful test status
          if ! gh api repos/${{ github.repository }}/commits/${{ github.event.inputs.checkout_ref }}/check-runs | jq '.check_runs[] | select(.conclusion == "success")' > /dev/null; then
            echo "No successful tests found for ${{ github.event.inputs.checkout_ref }}"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.checkout_ref }}

      - name: Deploy to environment
        run: |
          # Implement deployment steps based on the selected environment
          echo "Deploying to ${{ github.event.inputs.environment }}"
