name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service_name }}/

    steps:
      - uses: actions/checkout@v3

      - name: Run service ${{ inputs.service_name }} test script
        run: ./test.sh

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: calver

      - name: Build docker image
        run: make build

      - name: Release docker image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: make release
