name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service-name }}/

    steps:
      - uses: actions/checkout@v3

      - name: Run service ${{ inputs.service-name }} test script
        run: ./test.sh
